doc/adr/0001-architecture-decision-records.md

Add ADR to use ADRs

---

sonar-project.properties

Add basic SonarQube configuration

---

imls-raspberry-pi/internal/state/ephemeral.go
imls-raspberry-pi/internal/state/serial.go

SHA1 to SHA256 to fix security warning and changed
var name to HASH for consistency.

After reviewing Go documentation updated

---

.github/workflows/megalinter.yml
.mega-linter.yml

This should fix the permission issue some non-PR commits cause with Megalinter's status reporter

Fix status reporter for non-PRs

---

.github/workflows/codeql.yml
README.md
doc/adr/0004-basic-security-scanning.md

This adds codeql support for #15

Add codeql support

---

imls-backend/db/migrations/20220811195049_admin_schema.sql

Added a migration for the admin schema

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/task-form.yml
.github/ISSUE_TEMPLATE/user-story-form.yml

To compliment the User Story form, this is a form to create Tasks.  User Stories and Tasks are similar but complimentary: User Stories describe the "what" while Tasks describe the "how."

Initial import of new Task form

---

imls-windows-installer/install_go.ps1

Merging first script of several - this one installs Go 1.19

202 ps scripts build installer

---

imls-windows-installer/install_go.ps1
imls-windows-installer/install_innosetup.ps1

- Changed install_go to be a silent install
- Added script to install Inno Setup

202 PS build scripts: update to go install and added Inno Setup script

---

imls-windows-installer/build_session-counter.ps1
imls-windows-installer/build_wifi-hw-search.ps1
imls-windows-installer/session-counter_build_prereqs.ps1

Added a script that calls all the previous scripts

202 - Added last script

---

imls-backend/db/migrations/20220902032142_auth_role_permissions.sql
imls-backend/db/migrations/20220902033013_jwt_gen_func.sql
imls-backend/db/migrations/20220902033729_enable_pgcrypto.sql
imls-backend/docker-compose.yml

*** Needs to be reviewed before transition to production***

Creation of funcs for jwt_gen, add authenticator role and permission, update docker-compose

---

doc/github_practices.md

Team's github practices

---

imls-windows-installer/README.md
imls-windows-installer/session-counter.ini

small tweak to make it less tedious to do windows dev

setup default ini for windows local dev

---

imls-backend/.gitignore
imls-backend/README.md
imls-backend/poetry.lock
imls-backend/pyproject.toml
imls-backend/test/test_api.py

Quick poetry setup to run pytest/requests against the API. Sample tests included, haven't done anything fancy with the tests yet.

API test framework

---

imls-backend/db/migrations/20221017221845_create_sensor_info_func.sql

Code calling this function must trim the leading and trailing "( )"

Create the sensor_info function

---

imls-backend/README.md

Update README.md for pgAdmin instructions

---

imls-backend/docker-compose.yml
imls-backend/test/README.md
imls-backend/test/test_authentication.py
imls-wifi-sensor/cmd/linux-session-counter/session-counter.ini
imls-wifi-sensor/internal/config/config.go
imls-wifi-sensor/internal/session-counter-helper/api/api.go
imls-wifi-sensor/internal/session-counter-helper/session_counter/session-counter.go
imls-wifi-sensor/internal/session-counter-helper/tlp/heartbeat.go

Addresses https://github.com/IMLS/estimating-wifi/issues/117

heartbeat integration

---

.github/workflows/node.js.yml
imls-frontend/README.md
imls-frontend/package-lock.json
imls-frontend/package.json
imls-frontend/src/components/FetchData.spec.js
imls-frontend/src/components/FetchData.vue
imls-frontend/src/components/Heatmap.vue
imls-frontend/src/components/HeatmapWeeklyCalendar.vue
imls-frontend/src/components/Histogram.vue
imls-frontend/src/components/USWDSBreadcrumb.vue
imls-frontend/src/components/USWDSDatePicker.vue
imls-frontend/src/components/USWDSHeader.vue
imls-frontend/src/components/USWDSTable.vue
imls-frontend/src/views/PageHome.spec.js
imls-frontend/src/views/PageHome.vue
imls-frontend/src/views/PageLibrary.spec.js
imls-frontend/src/views/PageLibrary.vue
imls-frontend/src/views/PageSearch.spec.js
imls-frontend/src/views/PageSearch.vue
imls-frontend/src/views/PageState.spec.js
imls-frontend/src/views/PageState.vue
imls-frontend/test/setup.js
imls-frontend/vite.config.js

Replaced MSW with inline fetch mocks for more predictable/deterministic results. Fixed a few tests, too. And linted the files. These now run on open PR, thanks to Ben!

Fix frontend tests

---

.github/workflows/node.js.yml

Rudder, I have no idea why the file didn't make it before. Let's just try hitting it with a hammer. Here's the file again.

re-add node.js.yml file

---

imls-windows-installer/README.md

Updated README with session-counter.ini info

---

imls-wifi-sensor/internal/config/config.go
imls-windows-installer/session-counter.ini

Updated endpoint and port values

---

imls-frontend/src/store/store.js

This adds the test library which we called "Meenu's Apartment"

Add another test library
